// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEGvPg3xQVDdPOYKCTURdEOv1ttT73aEY',
    appId: '1:619446117462:web:d9b3edf072262ddc9fc7f7',
    messagingSenderId: '619446117462',
    projectId: 'zap-buzz',
    authDomain: 'zap-buzz.firebaseapp.com',
    storageBucket: 'zap-buzz.appspot.com',
    measurementId: 'G-3641JE1XH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlaopZ5kC789ZOo6SOyWE4qvVV297Eov8',
    appId: '1:619446117462:android:d293177d810f77d09fc7f7',
    messagingSenderId: '619446117462',
    projectId: 'zap-buzz',
    storageBucket: 'zap-buzz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMcrLgsTzWBSnXWmU5vTiEp7dFbD3CcpU',
    appId: '1:619446117462:ios:9f622b83d5ef912f9fc7f7',
    messagingSenderId: '619446117462',
    projectId: 'zap-buzz',
    storageBucket: 'zap-buzz.appspot.com',
    iosBundleId: 'com.example.zapbuzz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMcrLgsTzWBSnXWmU5vTiEp7dFbD3CcpU',
    appId: '1:619446117462:ios:9f622b83d5ef912f9fc7f7',
    messagingSenderId: '619446117462',
    projectId: 'zap-buzz',
    storageBucket: 'zap-buzz.appspot.com',
    iosBundleId: 'com.example.zapbuzz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEGvPg3xQVDdPOYKCTURdEOv1ttT73aEY',
    appId: '1:619446117462:web:39e60c7b2349ceb29fc7f7',
    messagingSenderId: '619446117462',
    projectId: 'zap-buzz',
    authDomain: 'zap-buzz.firebaseapp.com',
    storageBucket: 'zap-buzz.appspot.com',
    measurementId: 'G-513G3RCHB6',
  );
}
